name = "Hugo News"
license = "GPLv2"
licenselink = "https://github.com/johnrlive/hugo-news/blob/master/LICENSE.md"
description = "Mainroad is a responsive, clean and content-focused Hugo theme."
homepage = "https://github.com/johnrlive/hugo-news/"
tags = ["blog", "responsive", "widgets", "rss", "disqus", "google analytics", "wordpress"]
features = ["blog", "responsive", "widgets", "rss", "disqus", "wordpress"]
min_version = "0.36"

[author]
  name = "TheNerdLife"
  homepage = "https://github.com/johnrlive/hugo-news/"

# If porting an existing theme
[original]
  name = "Mainroad"
  homepage = "https://hugothemes.gitlab.io/mainroad/"
  repo = "https://github.com/Vimux/Mainroad/"
